#!/usr/bin/env bash
# ==============================================================================
# Install MyMonee Git Hooks
# Connects .git/hooks/pre-push -> scripts/git-pre-push.sh
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOKS_DIR="$ROOT_DIR/.git/hooks"

if [ ! -d "$HOOKS_DIR" ]; then
    echo "Error: .git/hooks directory not found. Are you in the root of the Git repo?" >&2
    exit 1
fi

PRE_PUSH_TARGET="$HOOKS_DIR/pre-push"
PRE_PUSH_SOURCE="$ROOT_DIR/scripts/git-pre-push.sh"

chmod +x "$PRE_PUSH_SOURCE"

# Create hook wrapper pointing to scripts/git-pre-push.sh
cat > "$PRE_PUSH_TARGET" << 'EOF'
#!/usr/bin/env bash
# Automatically generated by scripts/setup-git-hooks.sh
set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
HOOK_SCRIPT="$ROOT_DIR/scripts/git-pre-push.sh"

if [ -x "$HOOK_SCRIPT" ]; then
    exec "$HOOK_SCRIPT" "$@"
else
    echo "Warning: $HOOK_SCRIPT not found or not executable. Skipping pre-push checks." >&2
    exit 0
fi
EOF

chmod +x "$PRE_PUSH_TARGET"

echo "✓ Git pre-push hook installed successfully at: $PRE_PUSH_TARGET"
echo "  Target: $PRE_PUSH_SOURCE"
